# Use the official Python image as the base image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the app.py file to the container
COPY app.py .

# Run the Python script when the container starts
CMD ["python", "app.py"]

